AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'RefileRequestService'

Resources:
  RefileRequestService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 30
      Layers:
      - !Ref LibForPhp7Layer
      Environment:
        Variables:
          API_BASE_URL: https://qa-platform.nypl.org/api/v0.1/
          DB_CONNECT_STRING: pgsql:host=host.docker.internal;dbname=refile_requests_local;port=5432
          DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHkwdwYJKoZIhvcNAQcGoGowaAIBADBjBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDPGaENQWVqPt6yh1uAIBEIA2X1sJ9rt9I2bBysC4UAKitPzNN7OUBGKf2IF45D9xjQVRAYt6LjpSgcwMwVuj8kQN1Eebc9sd
          DB_USERNAME: postgres
          DEFAULT_LOGGING_LEVEL: debug
          IDENTITY_HEADER: X-NYPL-Identity
          JOB_SERVICE_URL: https://qa-platform.nypl.org/api/v0.1/jobs
          OAUTH_CLIENT_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHQwcgYJKoZIhvcNAQcGoGUwYwIBADBeBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBR6S5vFyVbDwMtUYAIBEIAxLwwXfRdgNE/ocKfKL1itSiiC+6n84fvGHtrxIp65t9bqroO1oWW1JGXlXzgI08Vnew==
          OAUTH_CLIENT_SCOPES: openid
          OAUTH_CLIENT_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyvMQfXXoTvaZyH3h4CARCAQ9BhNtkLZCXlZNW4+vzkhlTwUm9AUPqxvkDJTspogDoWFaYxnLezOfi101lIxnpPH+Ey4/ERpbCVJ/AjoLP/rpAyff8=
          OAUTH_TOKEN_URI: https://isso.nypl.org/oauth/token
          SCHEMA_BASE_URL: http://qa-platformdocs.nypl.org/api/v0.1/current-schemas
          SIP2_HOSTNAME: nypl-sierra-test.nypl.org
          SIP2_LOGIN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGYwZAYJKoZIhvcNAQcGoFcwVQIBADBQBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDItGIBVo9NwmtAjANAIBEIAjbwvua8488mA1Y3YTq9AzQg88IW4/F+1jkMflO1z3oBlNzrU=
          SIP2_PORT: 5550
          SIP2_TERMINAL_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGYwZAYJKoZIhvcNAQcGoFcwVQIBADBQBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDItGIBVo9NwmtAjANAIBEIAjbwvua8488mA1Y3YTq9AzQg88IW4/F+1jkMflO1z3oBlNzrU=
          SKIP_SIP2: true
          TIME_ZONE: America/New_York
          USE_JOB_SERVICE: 1
          SIERRA_BASE_API_URL: https://nypl-sierra-test.nypl.org/iii/sierra-api/v6
          SIERRA_OAUTH_TOKEN_URI: https://nypl-sierra-test.nypl.org/iii/sierra-api/v6/token
          SIERRA_OAUTH_CLIENT_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOcLof0wS+XIKrTc+QIBEIA3U0vf8ZaPKeyWsTF9VmuIThYmkQr1UYAvnbkSQVeXf90n+h/3JHk0WwoSPSVK9yG6/WxCzIJPkA==
          SIERRA_OAUTH_CLIENT_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDB20W+OqtkHEZQ7jvwIBEIAnZDf6KmlbYbOMmjkiF+Y57XtB0WfjGuAac5e7P88rk850OlHP7Q2y
      Events:
        ApiGetRefileRequestsPath:
          Type: Api
          Properties:
            Path: "/api/v0.1/refile-requests"
            Method: GET
        DocsPath:
          Type: Api
          Properties:
            Path: "/docs/refile-requests"
            Method: GET
  LibForPhp7Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lib-for-node10-wrapped-php7
      Description:
      ContentUri: node_modules/lib-for-node10-wrapped-php7-lambda-layer/
      CompatibleRuntimes:
      - nodejs10
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
